# Generated by Django 5.1 on 2026-05-03 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFigurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de figurinha',
                'verbose_name_plural': 'Categorias de figurinhas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('grupo', models.CharField(blank=True, max_length=20)),
                ('bandeira_emoji', models.CharField(blank=True, max_length=8)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Selecao',
                'verbose_name_plural': 'Selecoes',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('especial', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='figurinhas', to='album.categoriafigurinha')),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='album.selecao')),
            ],
            options={
                'verbose_name': 'Figurinha',
                'verbose_name_plural': 'Figurinhas',
                'ordering': ['selecao__ordem', 'ordem', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dei', 'Dei'), ('recebi', 'Recebi')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('figurinha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_troca', to='album.figurinha')),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='album.troca')),
            ],
            options={
                'verbose_name': 'Item de troca',
                'verbose_name_plural': 'Itens de troca',
                'ordering': ['tipo', 'figurinha__numero'],
            },
        ),
        migrations.CreateModel(
            name='ColecaoFigurinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecao', to=settings.AUTH_USER_MODEL)),
                ('figurinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to='album.figurinha')),
            ],
            options={
                'verbose_name': 'Colecao de figurinha',
                'verbose_name_plural': 'Colecoes de figurinhas',
                'ordering': ['figurinha__numero'],
                'unique_together': {('user', 'figurinha')},
            },
        ),
    ]
