# Generated by Django 5.1 on 2026-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='bandeira_codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
