# Generated by Django 5.1 on 2026-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_selecao_bandeira_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='codigo_album',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
