# Generated by Django 5.1 on 2026-05-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_selecao_codigo_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('codigo_album', models.CharField(max_length=8, unique=True)),
                ('cor', models.CharField(default='#245b3d', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secao especial',
                'verbose_name_plural': 'Secoes especiais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='figurinha',
            name='selecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='album.selecao'),
        ),
        migrations.AddField(
            model_name='figurinha',
            name='secao_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='album.secaoespecial'),
        ),
    ]
